const categories = [
  { name: "Carpintero", icon: "CA", count: "42 perfiles" },
  { name: "Electricista", icon: "EL", count: "58 perfiles" },
  { name: "Plomero", icon: "PL", count: "37 perfiles" },
  { name: "Gasista", icon: "GA", count: "21 perfiles" },
  { name: "Albanil", icon: "AL", count: "33 perfiles" },
  { name: "Pintor", icon: "PI", count: "28 perfiles" },
  { name: "Jardinero", icon: "JA", count: "18 perfiles" },
  { name: "Mecanico", icon: "ME", count: "25 perfiles" },
  { name: "Cerrajero", icon: "CE", count: "16 perfiles" },
  { name: "Limpieza", icon: "LI", count: "44 perfiles" },
  { name: "Estetica y Belleza", icon: "EB", count: "31 perfiles" },
  { name: "Salud", icon: "SA", count: "19 perfiles" },
  { name: "Profesores", icon: "PR", count: "22 perfiles" },
  { name: "Informatica", icon: "IN", count: "27 perfiles" },
  { name: "Mascotas", icon: "MA", count: "14 perfiles" },
  { name: "Mudanzas", icon: "MU", count: "11 perfiles" },
  { name: "Refrigeracion", icon: "RF", count: "20 perfiles" },
  { name: "Aires acondicionados", icon: "AA", count: "23 perfiles" },
];

const professionals = [
  {
    name: "Lucas Fernandez",
    profession: "Electricista matriculado",
    zone: "Zona Norte",
    description: "Instalaciones, tableros, mantenimiento y urgencias coordinadas para hogares y locales.",
    status: "Premium",
    photo: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=900&q=80",
    whatsapp: "https://wa.me/5491100000000",
  },
  {
    name: "Camila Rios",
    profession: "Limpieza profesional",
    zone: "CABA",
    description: "Limpieza profunda, oficinas, finales de obra y mantenimiento semanal con equipo propio.",
    status: "Gratuito",
    photo: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=900&q=80",
    whatsapp: "https://wa.me/5491100000001",
  },
  {
    name: "Martin Suarez",
    profession: "Plomero",
    zone: "Zona Oeste",
    description: "Reparacion de perdidas, destapaciones, instalacion de griferias y mantenimiento general.",
    status: "Premium",
    photo: "https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?auto=format&fit=crop&w=900&q=80",
    whatsapp: "https://wa.me/5491100000002",
  },
  {
    name: "Sofia Peralta",
    profession: "Estetica y belleza",
    zone: "La Plata",
    description: "Servicios a domicilio de manicuria, perfilado, maquillaje social y tratamientos faciales.",
    status: "Gratuito",
    photo: "https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=900&q=80",
    whatsapp: "https://wa.me/5491100000003",
  },
  {
    name: "Diego Molina",
    profession: "Refrigeracion",
    zone: "Zona Sur",
    description: "Instalacion y service de heladeras comerciales, camaras de frio y aires acondicionados.",
    status: "Premium",
    photo: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=900&q=80",
    whatsapp: "https://wa.me/5491100000004",
  },
  {
    name: "Natalia Castro",
    profession: "Profesora particular",
    zone: "Online y presencial",
    description: "Clases de matematica, apoyo escolar y preparacion de examenes para nivel secundario.",
    status: "Gratuito",
    photo: "https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=900&q=80",
    whatsapp: "https://wa.me/5491100000005",
  },
];
